---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore, vendor]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
search: true
title:       "HighLO"
description: "Project HighLO combines particle physics with finance to help protect commodity and financial markets from manipulation."
source_link: "https://github.com/HighLO/highlo.github.io"
favicon:     "assets/favicon.ico"
touch_icon:  "assets/apple-touch-icon.png"


### template colors, used site-wide via css ###
colors:
  darkblue:   '#0a4e80'
  mediumblue: '#0f75bc'
  brightblue: '#00aeef'
  green:      '#2ca296'
  black:      '#111111'
  white:      '#f8f8f8'
  bgwhite:    '#ffffff'
  bggray:     '#e9e9e9'
  bgblack:    '#2e2e2e'

kramdown:
  auto_ids:  false

collections:
  profiles:
  publications:
  news:
